#!/bin/bash
# Helper script for Render deployment

echo "🚀 Render Deployment Helper"
echo ""
echo "This script will guide you through deploying to Render."
echo ""
echo "Prerequisites:"
echo "  1. GitHub repository: Yash0067/backtesting0"
echo "  2. Render account (free at render.com)"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "📋 Deployment Checklist:"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect repository: Yash0067/backtesting0"
echo "4. Configure:"
echo "   - Name: backtesting-api"
echo "   - Root Directory: backend"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: uvicorn src.backend.app:app --host 0.0.0.0 --port \$PORT"
echo "5. Environment Variables:"
echo "   - PYTHON_VERSION = 3.11.0"
echo "   - ALLOWED_ORIGINS = https://frontend-nu-ten-75.vercel.app"
echo "6. Click 'Create Web Service'"
echo ""
echo "✅ After deployment, copy your Render URL and update frontend:"
echo "   cd ../frontend"
echo "   node auto-update-config.js https://your-render-url.onrender.com"
echo ""

